import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { client } from '../lib/sanity';

interface HomeProps {
  products: any;
  banners: any;
}

const Home: NextPage<HomeProps> = ({ banners, products }) => {
  return (
    <>
      <Head>
        <title>Tech Cube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <h1>Home</h1>
      </main>
      <footer>Footer</footer>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async ctx => {
  const productQuery = `*[_type == "product"]`;
  const bannerQuery = `*[_type == "banner"]`;

  let products, banners;
  try {
    products = await client.fetch(productQuery);
    banners = await client.fetch(bannerQuery);
  } catch (err) {
    console.log(err);
  }

  if (banners && products) {
    return {
      props: { banners, products },
    };
  }

  return {
    notFound: true,
  };
};
